<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1620189520155' stop='1620189640203'>
    <name>My Login application</name>
    <title>My Login application</title>
    <test-cases>
        <test-case start='1620189520155' status='broken' stop='1620189640193'>
            <name>should login with valid credentials</name>
            <title>should login with valid credentials</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome'/>
            </parameters>
            <steps/>
            <attachments/>
            <failure>
                <message>Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/tbm/git/ANZDemo/test/specs/example.e2e.js)</message>
                <stack-trace>Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/tbm/git/ANZDemo/test/specs/example.e2e.js)
                    at Test.Runnable._timeoutError (/Users/tbm/git/ANZDemo/node_modules/mocha/lib/runnable.js:442:10)
                    at Timeout.&lt;anonymous> (/Users/tbm/git/ANZDemo/node_modules/mocha/lib/runnable.js:252:24)
                    at listOnTimeout (internal/timers.js:531:17)
                    at processTimers (internal/timers.js:475:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>